name: gh-pages

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          DENO_INSTALL: /home/runner/.deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
          deno install --unstable --allow-read --allow-write --allow-net -n pagic https://deno.land/x/pagic@0.7.6/mod.ts
          pagic build

      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'hylerrix/deno-tutorial'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: deno-tutorial.js.org
